function runDTIAnalyses(fid,inFolder,outFolder,subject)
eddyCorrected=[outFolder ...
    subject '-Eddy-Current-Corrected'];
fprintf(fid,'%s \n',['eddy_correct ' ...
    inFolder subject '.nii '...
    eddyCorrected ' 0']);

fslRoied=[outFolder ...
    subject '-Eddy-Current-Corrected-ROI'];
fprintf(fid,'%s \n',['fslroi ' eddyCorrected '.nii.gz ' fslRoied ' 0 1']);

brainPure=[outFolder ...
    subject '-Eddy-Current-Corrected-Brain'];
fprintf(fid,'%s \n',['bet ' fslRoied '.nii.gz ' brainPure ' -f 0.3 -n -m']);


bvecsFile=[inFolder subject '.voxel_space.bvecs'];
bvalsFile=[inFolder subject '.bvals'];
dtiFitted=[outFolder ...
    subject '-dtiFitted'];
fprintf(fid,'%s \n',['dtifit --data=' eddyCorrected '.nii.gz --out=' ...
    dtiFitted ' --mask=' brainPure '_mask.nii.gz --bvecs=' bvecsFile ...
    ' --bvals=' bvalsFile]);


